/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.aop.example;

import com.annotations.Sysout;

public class App {

    public static void main(String[] args) {
    	testAOP();
    }
    
    @Sysout
    private static void testAOP() {
      System.out.println("Testing..");
    }
}
